// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jbURxL3XuiMBQsLhf7apui
// Component: BuqTNr9jIT
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Footer2 from "../../Footer2"; // plasmic-import: cYCn1eldGfZ/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_new_fathym_com.module.css"; // plasmic-import: jbURxL3XuiMBQsLhf7apui/projectcss
import sty from "./PlasmicHabistackFooter3.module.css"; // plasmic-import: BuqTNr9jIT/css

export type PlasmicHabistackFooter3__VariantMembers = {};

export type PlasmicHabistackFooter3__VariantsArgs = {};
type VariantPropType = keyof PlasmicHabistackFooter3__VariantsArgs;
export const PlasmicHabistackFooter3__VariantProps =
  new Array<VariantPropType>();

export type PlasmicHabistackFooter3__ArgsType = {};
type ArgPropType = keyof PlasmicHabistackFooter3__ArgsType;
export const PlasmicHabistackFooter3__ArgProps = new Array<ArgPropType>();

export type PlasmicHabistackFooter3__OverridesType = {
  root?: p.Flex<typeof Footer2>;
};

export interface DefaultHabistackFooter3Props {
  className?: string;
}

function PlasmicHabistackFooter3__RenderFunc(props: {
  variants: PlasmicHabistackFooter3__VariantsArgs;
  args: PlasmicHabistackFooter3__ArgsType;
  overrides: PlasmicHabistackFooter3__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <Footer2
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof Footer2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHabistackFooter3__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHabistackFooter3__VariantsArgs;
    args?: PlasmicHabistackFooter3__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHabistackFooter3__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHabistackFooter3__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHabistackFooter3__ArgProps,
      internalVariantPropNames: PlasmicHabistackFooter3__VariantProps
    });

    return PlasmicHabistackFooter3__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHabistackFooter3";
  } else {
    func.displayName = `PlasmicHabistackFooter3.${nodeName}`;
  }
  return func;
}

export const PlasmicHabistackFooter3 = Object.assign(
  // Top-level PlasmicHabistackFooter3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHabistackFooter3
    internalVariantProps: PlasmicHabistackFooter3__VariantProps,
    internalArgProps: PlasmicHabistackFooter3__ArgProps
  }
);

export default PlasmicHabistackFooter3;
/* prettier-ignore-end */
