// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jbURxL3XuiMBQsLhf7apui
// Component: cYCn1eldGfZ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput3 from "../../TextInput3"; // plasmic-import: KEjkl_jgeZ8/component
import Button3 from "../../Button3"; // plasmic-import: wspG9_I0g7M/component
import IconLink2 from "../../IconLink2"; // plasmic-import: bNtDNMxjRVWu/component

import { useScreenVariants as useScreenVariantsbzFq34BwReL2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BzFq34bwReL2/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_new_fathym_com.module.css"; // plasmic-import: jbURxL3XuiMBQsLhf7apui/projectcss
import sty from "./PlasmicFooter2.module.css"; // plasmic-import: cYCn1eldGfZ/css

import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: _s4zGGUKFzul/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: VSVBWWleY_Z/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: reqCYX4Vc1Lv/icon
import TwitterIconIcon from "./icons/PlasmicIcon__TwitterIcon"; // plasmic-import: OiyLcqCpAFbm/icon
import InstagramGlyphBlackLogowinesvgIcon from "./icons/PlasmicIcon__InstagramGlyphBlackLogowinesvg"; // plasmic-import: uZwvHnmln5Ol/icon
import GithubIconIcon from "./icons/PlasmicIcon__GithubIcon"; // plasmic-import: 4MOEJCX4_jYc/icon
import LinkedinLinesvgIcon from "./icons/PlasmicIcon__LinkedinLinesvg"; // plasmic-import: bM5auaV8f9nE/icon
import FacebookIconIcon from "./icons/PlasmicIcon__FacebookIcon"; // plasmic-import: yeSC35cwTR9f/icon

export type PlasmicFooter2__VariantMembers = {};

export type PlasmicFooter2__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooter2__VariantsArgs;
export const PlasmicFooter2__VariantProps = new Array<VariantPropType>();

export type PlasmicFooter2__ArgsType = {};
type ArgPropType = keyof PlasmicFooter2__ArgsType;
export const PlasmicFooter2__ArgProps = new Array<ArgPropType>();

export type PlasmicFooter2__OverridesType = {
  root2?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  httpswwwfathymcom?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfathymcomiot?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwhabistackcom?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwproadjectcom?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfathymcomdocs?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfathymcomblog?: p.Flex<"a"> & Partial<LinkProps>;
  mailtosupportfathymcom?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfathymcom2?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfathymcom3?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfathymcom4?: p.Flex<"a"> & Partial<LinkProps>;
  textInput3?: p.Flex<typeof TextInput3>;
  button3?: p.Flex<typeof Button3>;
  httpstwittercomFathymIt?: p.Flex<"a"> & Partial<LinkProps>;
  fathymIt?: p.Flex<typeof IconLink2>;
  twitter?: p.Flex<"svg">;
  httpswwwinstagramcomfathymit2?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwinstagramcomfathymit?: p.Flex<typeof IconLink2>;
  instagram?: p.Flex<"svg">;
  httpsgithubcomfathym?: p.Flex<"a"> & Partial<LinkProps>;
  httpsgithubcomfathym4?: p.Flex<typeof IconLink2>;
  gitHub2?: p.Flex<"svg">;
  httpswwwlinkedincomcompanyfathym2?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwlinkedincomcompanyfathym?: p.Flex<typeof IconLink2>;
  linkedin?: p.Flex<"svg">;
  httpswwwfacebookcomFathymInc2?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfacebookcomFathymInc?: p.Flex<typeof IconLink2>;
  facebook?: p.Flex<"svg">;
};

export interface DefaultFooter2Props {
  className?: string;
}

function PlasmicFooter2__RenderFunc(props: {
  variants: PlasmicFooter2__VariantsArgs;
  args: PlasmicFooter2__ArgsType;
  overrides: PlasmicFooter2__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbzFq34BwReL2()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root2"}
      data-plasmic-override={overrides.root2}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root2
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox___2KxT4)} />

      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={"" as const}
        className={classNames(sty.img)}
        displayHeight={"185px" as const}
        displayMaxHeight={"75px" as const}
        displayMaxWidth={"75%" as const}
        displayMinHeight={"0" as const}
        displayMinWidth={"0" as const}
        displayWidth={"auto" as const}
        loading={"lazy" as const}
        src={{
          src: "/plasmic/new_fathym_com/images/fathymLogoAqua01400Pxlspng.png",
          fullWidth: 400,
          fullHeight: 129,
          aspectRatio: undefined
        }}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__oowL0)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___1Gr70)}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__dEjnk)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fOqet
              )}
            >
              {"Products"}
            </div>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfathymcom"}
              data-plasmic-override={overrides.httpswwwfathymcom}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwfathymcom
              )}
              component={Link}
              href={"https://www.fathym.com/" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Fathym Platform"}
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfathymcomiot"}
              data-plasmic-override={overrides.httpswwwfathymcomiot}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwfathymcomiot
              )}
              component={Link}
              href={"https://www.fathym.com/iot" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"IoT Ensemble"}
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwhabistackcom"}
              data-plasmic-override={overrides.httpswwwhabistackcom}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwhabistackcom
              )}
              component={Link}
              href={"https://www.habistack.com/" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Habistack"}
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwproadjectcom"}
              data-plasmic-override={overrides.httpswwwproadjectcom}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwproadjectcom
              )}
              component={Link}
              href={"https://www.proadject.com/" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"pROADject"}
            </p.PlasmicLink>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__mnNvy)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hwXye
              )}
            >
              {"Resources"}
            </div>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfathymcomdocs"}
              data-plasmic-override={overrides.httpswwwfathymcomdocs}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwfathymcomdocs
              )}
              component={Link}
              href={"https://www.fathym.com/docs" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Documentation"}
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfathymcomblog"}
              data-plasmic-override={overrides.httpswwwfathymcomblog}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwfathymcomblog
              )}
              component={Link}
              href={"https://www.fathym.com/blog/" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Blog"}
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"mailtosupportfathymcom"}
              data-plasmic-override={overrides.mailtosupportfathymcom}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.mailtosupportfathymcom
              )}
              component={Link}
              href={"mailto:support@fathym.com" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Support"}
            </p.PlasmicLink>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__hfLsa)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qkJbh
              )}
            >
              {"Company"}
            </div>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfathymcom2"}
              data-plasmic-override={overrides.httpswwwfathymcom2}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwfathymcom2
              )}
              component={Link}
              href={"https://www.fathym.com/" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Terms of Services"}
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfathymcom3"}
              data-plasmic-override={overrides.httpswwwfathymcom3}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwfathymcom3
              )}
              component={Link}
              href={"https://www.fathym.com/" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Privacy Policy"}
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfathymcom4"}
              data-plasmic-override={overrides.httpswwwfathymcom4}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.httpswwwfathymcom4
              )}
              component={Link}
              href={"https://www.fathym.com/" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              {"Enterprise Agreement"}
            </p.PlasmicLink>
          </p.Stack>

          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__eMqu5)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ui6Ra
                )}
              >
                {"Subscribe"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dkdii
                )}
              >
                {"Get the latest news and articles to your inbox every month."}
              </div>

              <TextInput3
                data-plasmic-name={"textInput3"}
                data-plasmic-override={overrides.textInput3}
                className={classNames("__wab_instance", sty.textInput3)}
                endIcon={
                  <Button3
                    data-plasmic-name={"button3"}
                    data-plasmic-override={overrides.button3}
                    className={classNames("__wab_instance", sty.button3)}
                    color={"clear" as const}
                    size={"compact" as const}
                    startIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__pYky)}
                        role={"img"}
                      />
                    }
                  >
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__b1Sve)}
                      role={"img"}
                    />
                  </Button3>
                }
                fontSize={"small" as const}
                placeholder={"Your email" as const}
                showEndIcon={true}
              />
            </p.Stack>
          ) : null}
        </p.Stack>
      </p.Stack>

      <div className={classNames(projectcss.all, sty.freeBox__jyFgI)} />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__a3Sut)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__kmVgh)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__yizef
            )}
          >
            {"Copyright 2022 Fathym. All rights reserved."}
          </div>
        </div>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__tRQL)}
        >
          <p.PlasmicLink
            data-plasmic-name={"httpstwittercomFathymIt"}
            data-plasmic-override={overrides.httpstwittercomFathymIt}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.httpstwittercomFathymIt
            )}
            component={Link}
            href={"https://twitter.com/FathymIt" as const}
            platform={"nextjs"}
            target={"_blank" as const}
          >
            <IconLink2
              data-plasmic-name={"fathymIt"}
              data-plasmic-override={overrides.fathymIt}
              icon={
                <TwitterIconIcon
                  data-plasmic-name={"twitter"}
                  data-plasmic-override={overrides.twitter}
                  className={classNames(projectcss.all, sty.twitter)}
                  role={"img"}
                />
              }
            />
          </p.PlasmicLink>

          <p.PlasmicLink
            data-plasmic-name={"httpswwwinstagramcomfathymit2"}
            data-plasmic-override={overrides.httpswwwinstagramcomfathymit2}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.httpswwwinstagramcomfathymit2
            )}
            component={Link}
            href={"https://www.instagram.com/fathymit/" as const}
            platform={"nextjs"}
            target={"_blank" as const}
          >
            <IconLink2
              data-plasmic-name={"httpswwwinstagramcomfathymit"}
              data-plasmic-override={overrides.httpswwwinstagramcomfathymit}
              icon={
                <InstagramGlyphBlackLogowinesvgIcon
                  data-plasmic-name={"instagram"}
                  data-plasmic-override={overrides.instagram}
                  className={classNames(projectcss.all, sty.instagram)}
                  role={"img"}
                />
              }
            />
          </p.PlasmicLink>

          <p.PlasmicLink
            data-plasmic-name={"httpsgithubcomfathym"}
            data-plasmic-override={overrides.httpsgithubcomfathym}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.httpsgithubcomfathym
            )}
            component={Link}
            href={"https://github.com/fathym" as const}
            platform={"nextjs"}
            target={"_blank" as const}
          >
            <IconLink2
              data-plasmic-name={"httpsgithubcomfathym4"}
              data-plasmic-override={overrides.httpsgithubcomfathym4}
              icon={
                <GithubIconIcon
                  data-plasmic-name={"gitHub2"}
                  data-plasmic-override={overrides.gitHub2}
                  className={classNames(projectcss.all, sty.gitHub2)}
                  role={"img"}
                />
              }
            />
          </p.PlasmicLink>

          <p.PlasmicLink
            data-plasmic-name={"httpswwwlinkedincomcompanyfathym2"}
            data-plasmic-override={overrides.httpswwwlinkedincomcompanyfathym2}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.httpswwwlinkedincomcompanyfathym2
            )}
            component={Link}
            href={"https://www.linkedin.com/company/fathym" as const}
            platform={"nextjs"}
            target={"_blank" as const}
          >
            <IconLink2
              data-plasmic-name={"httpswwwlinkedincomcompanyfathym"}
              data-plasmic-override={overrides.httpswwwlinkedincomcompanyfathym}
              icon={
                <LinkedinLinesvgIcon
                  data-plasmic-name={"linkedin"}
                  data-plasmic-override={overrides.linkedin}
                  className={classNames(projectcss.all, sty.linkedin)}
                  role={"img"}
                />
              }
            />
          </p.PlasmicLink>

          <p.PlasmicLink
            data-plasmic-name={"httpswwwfacebookcomFathymInc2"}
            data-plasmic-override={overrides.httpswwwfacebookcomFathymInc2}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.httpswwwfacebookcomFathymInc2
            )}
            component={Link}
            href={"https://www.facebook.com/FathymInc/" as const}
            platform={"nextjs"}
            target={"_blank" as const}
          >
            <IconLink2
              data-plasmic-name={"httpswwwfacebookcomFathymInc"}
              data-plasmic-override={overrides.httpswwwfacebookcomFathymInc}
              icon={
                <FacebookIconIcon
                  data-plasmic-name={"facebook"}
                  data-plasmic-override={overrides.facebook}
                  className={classNames(projectcss.all, sty.facebook)}
                  role={"img"}
                />
              }
            />
          </p.PlasmicLink>
        </p.Stack>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root2: [
    "root2",
    "img",
    "httpswwwfathymcom",
    "httpswwwfathymcomiot",
    "httpswwwhabistackcom",
    "httpswwwproadjectcom",
    "httpswwwfathymcomdocs",
    "httpswwwfathymcomblog",
    "mailtosupportfathymcom",
    "httpswwwfathymcom2",
    "httpswwwfathymcom3",
    "httpswwwfathymcom4",
    "textInput3",
    "button3",
    "httpstwittercomFathymIt",
    "fathymIt",
    "twitter",
    "httpswwwinstagramcomfathymit2",
    "httpswwwinstagramcomfathymit",
    "instagram",
    "httpsgithubcomfathym",
    "httpsgithubcomfathym4",
    "gitHub2",
    "httpswwwlinkedincomcompanyfathym2",
    "httpswwwlinkedincomcompanyfathym",
    "linkedin",
    "httpswwwfacebookcomFathymInc2",
    "httpswwwfacebookcomFathymInc",
    "facebook"
  ],
  img: ["img"],
  httpswwwfathymcom: ["httpswwwfathymcom"],
  httpswwwfathymcomiot: ["httpswwwfathymcomiot"],
  httpswwwhabistackcom: ["httpswwwhabistackcom"],
  httpswwwproadjectcom: ["httpswwwproadjectcom"],
  httpswwwfathymcomdocs: ["httpswwwfathymcomdocs"],
  httpswwwfathymcomblog: ["httpswwwfathymcomblog"],
  mailtosupportfathymcom: ["mailtosupportfathymcom"],
  httpswwwfathymcom2: ["httpswwwfathymcom2"],
  httpswwwfathymcom3: ["httpswwwfathymcom3"],
  httpswwwfathymcom4: ["httpswwwfathymcom4"],
  textInput3: ["textInput3", "button3"],
  button3: ["button3"],
  httpstwittercomFathymIt: ["httpstwittercomFathymIt", "fathymIt", "twitter"],
  fathymIt: ["fathymIt", "twitter"],
  twitter: ["twitter"],
  httpswwwinstagramcomfathymit2: [
    "httpswwwinstagramcomfathymit2",
    "httpswwwinstagramcomfathymit",
    "instagram"
  ],
  httpswwwinstagramcomfathymit: ["httpswwwinstagramcomfathymit", "instagram"],
  instagram: ["instagram"],
  httpsgithubcomfathym: [
    "httpsgithubcomfathym",
    "httpsgithubcomfathym4",
    "gitHub2"
  ],
  httpsgithubcomfathym4: ["httpsgithubcomfathym4", "gitHub2"],
  gitHub2: ["gitHub2"],
  httpswwwlinkedincomcompanyfathym2: [
    "httpswwwlinkedincomcompanyfathym2",
    "httpswwwlinkedincomcompanyfathym",
    "linkedin"
  ],
  httpswwwlinkedincomcompanyfathym: [
    "httpswwwlinkedincomcompanyfathym",
    "linkedin"
  ],
  linkedin: ["linkedin"],
  httpswwwfacebookcomFathymInc2: [
    "httpswwwfacebookcomFathymInc2",
    "httpswwwfacebookcomFathymInc",
    "facebook"
  ],
  httpswwwfacebookcomFathymInc: ["httpswwwfacebookcomFathymInc", "facebook"],
  facebook: ["facebook"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root2: "div";
  img: typeof p.PlasmicImg;
  httpswwwfathymcom: "a";
  httpswwwfathymcomiot: "a";
  httpswwwhabistackcom: "a";
  httpswwwproadjectcom: "a";
  httpswwwfathymcomdocs: "a";
  httpswwwfathymcomblog: "a";
  mailtosupportfathymcom: "a";
  httpswwwfathymcom2: "a";
  httpswwwfathymcom3: "a";
  httpswwwfathymcom4: "a";
  textInput3: typeof TextInput3;
  button3: typeof Button3;
  httpstwittercomFathymIt: "a";
  fathymIt: typeof IconLink2;
  twitter: "svg";
  httpswwwinstagramcomfathymit2: "a";
  httpswwwinstagramcomfathymit: typeof IconLink2;
  instagram: "svg";
  httpsgithubcomfathym: "a";
  httpsgithubcomfathym4: typeof IconLink2;
  gitHub2: "svg";
  httpswwwlinkedincomcompanyfathym2: "a";
  httpswwwlinkedincomcompanyfathym: typeof IconLink2;
  linkedin: "svg";
  httpswwwfacebookcomFathymInc2: "a";
  httpswwwfacebookcomFathymInc: typeof IconLink2;
  facebook: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooter2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooter2__VariantsArgs;
    args?: PlasmicFooter2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFooter2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFooter2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter2__ArgProps,
      internalVariantPropNames: PlasmicFooter2__VariantProps
    });

    return PlasmicFooter2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root2") {
    func.displayName = "PlasmicFooter2";
  } else {
    func.displayName = `PlasmicFooter2.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter2 = Object.assign(
  // Top-level PlasmicFooter2 renders the root element
  makeNodeComponent("root2"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    httpswwwfathymcom: makeNodeComponent("httpswwwfathymcom"),
    httpswwwfathymcomiot: makeNodeComponent("httpswwwfathymcomiot"),
    httpswwwhabistackcom: makeNodeComponent("httpswwwhabistackcom"),
    httpswwwproadjectcom: makeNodeComponent("httpswwwproadjectcom"),
    httpswwwfathymcomdocs: makeNodeComponent("httpswwwfathymcomdocs"),
    httpswwwfathymcomblog: makeNodeComponent("httpswwwfathymcomblog"),
    mailtosupportfathymcom: makeNodeComponent("mailtosupportfathymcom"),
    httpswwwfathymcom2: makeNodeComponent("httpswwwfathymcom2"),
    httpswwwfathymcom3: makeNodeComponent("httpswwwfathymcom3"),
    httpswwwfathymcom4: makeNodeComponent("httpswwwfathymcom4"),
    textInput3: makeNodeComponent("textInput3"),
    button3: makeNodeComponent("button3"),
    httpstwittercomFathymIt: makeNodeComponent("httpstwittercomFathymIt"),
    fathymIt: makeNodeComponent("fathymIt"),
    twitter: makeNodeComponent("twitter"),
    httpswwwinstagramcomfathymit2: makeNodeComponent(
      "httpswwwinstagramcomfathymit2"
    ),
    httpswwwinstagramcomfathymit: makeNodeComponent(
      "httpswwwinstagramcomfathymit"
    ),
    instagram: makeNodeComponent("instagram"),
    httpsgithubcomfathym: makeNodeComponent("httpsgithubcomfathym"),
    httpsgithubcomfathym4: makeNodeComponent("httpsgithubcomfathym4"),
    gitHub2: makeNodeComponent("gitHub2"),
    httpswwwlinkedincomcompanyfathym2: makeNodeComponent(
      "httpswwwlinkedincomcompanyfathym2"
    ),
    httpswwwlinkedincomcompanyfathym: makeNodeComponent(
      "httpswwwlinkedincomcompanyfathym"
    ),
    linkedin: makeNodeComponent("linkedin"),
    httpswwwfacebookcomFathymInc2: makeNodeComponent(
      "httpswwwfacebookcomFathymInc2"
    ),
    httpswwwfacebookcomFathymInc: makeNodeComponent(
      "httpswwwfacebookcomFathymInc"
    ),
    facebook: makeNodeComponent("facebook"),

    // Metadata about props expected for PlasmicFooter2
    internalVariantProps: PlasmicFooter2__VariantProps,
    internalArgProps: PlasmicFooter2__ArgProps
  }
);

export default PlasmicFooter2;
/* prettier-ignore-end */
